# Who Lives on the Titanic?

In [12]:
#code to import a csv and convert it to a numpy array
#import the numpy library
import statistics
import numpy as np
#open the file
raw_data = open("titanic.csv")
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
#'shape' is the dimensions of the matrix
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:3]
y = dataset[:,3]
print(X)
print(y)


(2201, 4)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 ..., 
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]


In [13]:
# What is the average accuracy of the following three machine learning algorithms on this dataset: DecisionTree, KNeighbors, RandomForest? (Hint: look at the code file from last week to figure out how to use the new algorithms)
# Who would've survived?
#a. An adult male in the 3rd class
#b. An adult female in 1st class
#c. A female child in 1st class
#3. Which is the most important determining feature in this dataset? (Hint: try removing features one at a time, and observe the results)

In [14]:
# Featture Column 1   Class (0 = crew, 1 = first, 2 = second, 3 = third)
# Feature Column 2    Age (1 = adult, 0 = child)
# Feature Column 3    Sex   (1 = male, 0 = female)
# Target Column 4   Survived (1 = yes, 0 = no)

In [15]:
from sklearn import datasets
import random
from sklearn.cross_validation import train_test_split



In [16]:
#Decision tree
import random
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(tree_predictions, y_test))

#0.791, 0.784, 0.794, 0.782, 0.798

tree=[0.791, 0.784, 0.794, 0.782, 0.789]

print("average of decision tree accuracy", statistics.mean(tree))



0.799273387829
average of decision tree accuracy 0.788


In [17]:
#KNeighbors
import random
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import neighbors
knn_classifier = neighbors.KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, y_train)
knn_predictions = knn_classifier.predict(X_test)

print(accuracy_score(knn_predictions, y_test))

#0.786，0.747， 0.774， .785， 0.795

neighbors=[0.786,0.747,0.774, 0.785, 0.795]

print("average of K neighbors accuracy", statistics.mean(neighbors))


0.765667574932
average of K neighbors accuracy 0.7774


In [18]:
#Random Forest
import random
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print(accuracy_score(rf_predictions, y_test))

#0.802，0.781， 0.782，0.780，0.776

forest=[0.802, 0.781, 0.782,.780, 0.776]

print("average of random forest accuracy", statistics.mean(forest))


0.782016348774
average of random forest accuracy 0.7842


In [19]:
# For me, the most accurate machine algorithm was Random forest.

# Part 2

In [55]:
#2. Using the most accurate algorithm, predict whether the following imaginary people would have survived:
#an adult male in the 3rd class died


from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("adult male in third class is probably dead ", clf.predict([[3,1,1]]))



adult male in third class is probably dead  [ 0.]


In [49]:
# an adult female in 1st class lived
from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[1,1,0]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)


print("adult female in first class is probably alive ", clf.predict([[1,1,0]]))

adult female in first class is probably alive  [ 1.]


In [48]:
#a female child in 1st class lived
from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[1,0,0]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)


print("child female in first class is probably alive", clf.predict([[1,0,0]]))

child female in first class is probably alive [ 1.]


# Part 3

In [56]:
#what if the man was in first class dead? (dead)

from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("Adult male in first class is probably dead", clf.predict([[1,1,1]]))

Adult male in first class is probably dead [ 0.]


In [42]:
#what if the man was child dead? (still dead)

from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("Child male in third class is probably dead ", clf.predict([[3,0,1]]))

child male in third class is probably dead  [ 0.]


In [60]:
#What if the male was a female dead? (dead)
from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("Female child in 3rd class is probably dead ", clf.predict([[3,1,0]]))

Female in 3rd class is probably dead  [ 0.]


In [63]:
#What if the male child was in Second class? (Alive)

from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("Child male in second class is probably alive ", clf.predict([[2,0,1]]))

Child male in second class is probably alive  [ 0.]


In [67]:
#What if the female was part of the crew? (ALIVE!!!!!)

from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("Female adult in the crew was probably alive ", clf.predict([[0,1,0]]))

Female adult in the crew was probably alive  [ 1.]


In [69]:
#What if the male was part of the crew? (Dead)

from sklearn import ensemble
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
clf= ensemble.RandomForestClassifier()
clf=clf.fit(X,y)
clf.predict([[3,1,1]])

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print("Male adult in the crew was probably alive ", clf.predict([[0,1,1]]))

Male e adult in the crew was probably alive  [ 0.]


There was no one determining class in order to survive. You need a mixture of at least two for the males. For me, I took a look at an adult male in the third class. I tried changing him to being in first class, but he was still dead. Making him either a female or a child didn’t change that either (I didn't mess with the crew because they were probably dead). From the first few observations I could already see that females would probably live unless they were in a lower class. So the question now was, "what would allow a male to live"? So I changed him to being a child and found that the only way a child were to not live, was if they were in the third class (I checked, and there were no children in the crew). In terms of adult men, all of had a high probability of dying. Based off of this, I can say that the majority of people that lived were middle class to upper class females lived (all children except for 3rd class males lived). So pretty much all males were probably going to die, and since this was in the early 1900's men probably had the duty to protect the women and kids. If you were a third class kid regardless male or female, nobody really cared about you and you were probably going to die.  

 However, interesting enough although third class adult females died, they didn't if they were in the crew. My only hypotheses for this was they had to get on boats to instruct people or were the first in the crew to get escorted out. However the male crew members were probably dead.
